### ISSUE TITLE
Require a directory

### ISSUE THREAD

**Issue by codingtwinky** [pocesar/grunt-mocha-istanbul#47]
It would be nice if an entire directory can be included instead of individual files

```javascript
    mocha_istanbul: {
      unit: {
        src: './test',
        options: {
          mask: 'spec.*.js',
          require: ['./source/**/*.js'],
        }
      }
    }
```

```
Error: Cannot find module './source/**/*.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/junkkim/github/ungit/node_modules/mocha/bin/_mocha:304:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/junkkim/github/ungit/node_modules/mocha/bin/_mocha:303:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/Users/junkkim/github/ungit/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at runFn (/Users/junkkim/github/ungit/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /Users/junkkim/github/ungit/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /Users/junkkim/github/ungit/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /Users/junkkim/github/ungit/node_modules/async/lib/async.js:52:16
    at /Users/junkkim/github/ungit/node_modules/async/lib/async.js:363:13
    at /Users/junkkim/github/ungit/node_modules/async/lib/async.js:52:16
    at done (/Users/junkkim/github/ungit/node_modules/async/lib/async.js:248:21)
    at /Users/junkkim/github/ungit/node_modules/async/lib/async.js:44:16
    at /Users/junkkim/github/ungit/node_modules/async/lib/async.js:360:17
    at LOOP (fs.js:1474:14)
    at process._tickCallback (node.js:355:11)
```

**Comment by pocesar** [comment]
that's a mocha limitation, maybe you could try ask them for this feature

**Comment by codingtwinky** [comment]
so I understand how they are encouraging shell command when mocha is run in command line like [answered here](http://stackoverflow.com/a/10754286/1834377).

However, I was hoping this plugin would go extra mile and do this in lovely way.  Maybe I will give a shot and send you a PR later and let you evaluate.

**Comment by pocesar** [comment]
grunt could expand the globs, yeah

**Comment by pocesar** [comment]
it's now possible to use globs in require on version 5.0.0
